name: static-web-app
on:
  push:
    branches:
      - main
    paths:
      - enhexen/*
      - .github/workflows/static-web-app.yml
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          #repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "enhexen/src" # App source code path relative to repository root
          output_location: "dist" # Built app content directory, relative to app_location - optional
          app_build_command: 'npm run build'
          skip_api_build: true